######################
### USING NOCTALIA ###
######################
exec-once = noctalia

####################
### USING WAYBAR ###
####################
# exec-once = waybar
# exec-once = swaync &
# exec-once = copyq &
# exec-once = hypridle
# exec-once = pidof hyprlock || hyprlock
# exec-once = blueman-applet
# exec-once = nm-applet --indicator

#######################
### USING HYPRPAPER ###
#######################
# exec-once = hyprpaper
# exec-once = $HOME/.config/hypr/scripts/hyprpaper_randomize.sh

# Misc
exec-once = [workspace 1 silent] $browser
exec-once = [workspace 3 silent] $terminal

# GTK theme settings
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Breeze'
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'