#################
### AUTOSTART ###
#################

# Background Programs
exec-once = themectl recover
exec-once = pidof hyprlock || themectl launch hyprlock
exec-once = hypridle
exec-once = themectl launch hyprpaper
exec-once = blueman-applet
exec-once = nm-applet --indicator
exec-once = themectl launch swaync
exec-once = copyq &
exec-once = themectl launch waybar
exec-once = bitwarden-desktop &

# Misc
exec-once = [workspace 10 silent] discord
exec-once = [workspace 9 silent] steam
exec-once = [workspace 8 silent] nextcloud
exec-once = [workspace 3 silent] $terminal
exec-once = [workspace 1 silent] $browser

# Specials
exec-once = themectl wallpaper next
exec-once = $HOME/.config/hypr/scripts/battery_notify.sh
