###################
### ENVIRONMENT ###
###################

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt5ct # Qt theme settings
env = GTK_THEME,Breeze-Dark # Apply the selected GTK theme
env = PATH,$HOME/.local/bin:$PATH

###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = nautilus
$browser = vivaldi
$menu = noctalia msg panel-toggle launcher
