$basePath = $HOME/.config/hypr/confs

source = $basePath/environment.conf
source = $basePath/monitors.conf
source = $basePath/appearance.conf
source = $basePath/permissions.conf
source = $basePath/windows.conf
source = $basePath/animations.conf
source = $basePath/input.conf
source = $basePath/autostart.conf
source = $basePath/bindings.conf

# HyprEmoji config
source = $HOME/.config/hypremoji/hypremoji.conf
