# You can add or remove programs from this list to customize your installation
misc_programs=(
    "git"
    "wget"
    "curl"
    "unzip"
    "tar"
    "alacritty"
    "loupe"
    "gst-plugin-pipewire" 
    "gst-libav" 
    "gst-plugins-bad" 
    "gst-plugins-good"
    "gst-plugins-ugly"
    "pipewire" 
    "bluez" 
    "bluez-utils" 
    "blueman" 
    "swaync" 
    "copyq"
    "mpv" 
    "vlc" 
    "ffmpeg" 
    "imagemagick"
    "pamixer" 
    "pavucontrol"
    "grim" 
    "slurp"
    "vivaldi" 
    "nautilus" 
    "discord" 
    "torbrowser-launcher"
)

sudo pacman -S "${misc_programs[@]}"