[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/tokyo-night.toml"
]

[window]
blur = true
opacity = 0.9
dimensions = { columns = 120, lines = 22 }

[bell]
animation = "EaseOutExpo"
duration = 0

[font.glyph_offset]
x = 0
y = 0

[font]
normal.family = "JetBrainsMono"
size = 18.0
